package Modelos;

import java.io.Serializable;

public enum CasesEnCliente implements Serializable {
    NADA,
    SIGUIENTETURNO,
    RECIBIRMENSAJE,
    RECIBIRACCION,
    RECIBIROFERTA,
    OFERTAACEPTADA,
    DEVOLVERGRAFO,
    SETGRAFOENEMIGO,
    RECIBIROFERTAACERO,
    OFERTAACEPTADAACERO,
    SERATACADO,
    CONSEGUIRFUENTE,
    PONERENBITACORA,
    ALGUIENGANO,
    YOGANE

}
