package Modelos;

public enum CasesEnThreadServidor {
    NADA,
    MANDARMENSAJE,
    MANDARACCION,
    DEVOLVERNOMBRESOPONENTES,
    PROPONERVENTA,
    PONERENOBJETO,
    CONSEGUIRGRAFOENEMIGO,
    ATACARCANON,
    ATACARCANONMULT,
    ATACARBOMBA,
    ATACARCBR,
    PROPONERVENTAACERO,
    ATACARKRAKEN,
    PERDER
}
